package export

import "fmt"

const fastapiAppTmpl = `#!/usr/bin/env python3
"""{{ .AgentName }} — FastAPI wrapper — Generated by Trovery Forge"""

import json
import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
{{ if eq .Provider "anthropic" }}
from anthropic import Anthropic

client = Anthropic()
{{ else }}
from openai import OpenAI

client = OpenAI()
{{ end }}

MODEL = "{{ .Model }}"
SYSTEM_PROMPT = """{{ .SystemPrompt }}"""


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application startup/shutdown."""
    yield


app = FastAPI(
    title="{{ .AgentName }}",
    description="Agent API — Generated by Trovery Forge",
    lifespan=lifespan,
)


class InvokeRequest(BaseModel):
    message: str


class InvokeResponse(BaseModel):
    response: str


@app.get("/health")
async def health():
    return {"status": "ok", "agent": "{{ .AgentName }}", "model": MODEL}

{{ if eq .Provider "anthropic" }}
@app.post("/invoke", response_model=InvokeResponse)
async def invoke(req: InvokeRequest):
    response = client.messages.create(
        model=MODEL,
        max_tokens={{ .MaxTokens }},
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": req.message}],
    )
    text = ""
    for block in response.content:
        if hasattr(block, "text"):
            text += block.text
    return InvokeResponse(response=text)


@app.post("/invoke/stream")
async def invoke_stream(req: InvokeRequest):
    def generate():
        with client.messages.stream(
            model=MODEL,
            max_tokens={{ .MaxTokens }},
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": req.message}],
        ) as stream:
            for text in stream.text_stream:
                yield f"data: {json.dumps({'text': text})}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(generate(), media_type="text/event-stream")
{{ else }}
@app.post("/invoke", response_model=InvokeResponse)
async def invoke(req: InvokeRequest):
    response = client.chat.completions.create(
        model=MODEL,
        max_tokens={{ .MaxTokens }},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": req.message},
        ],
    )
    return InvokeResponse(response=response.choices[0].message.content or "")


@app.post("/invoke/stream")
async def invoke_stream(req: InvokeRequest):
    def generate():
        stream = client.chat.completions.create(
            model=MODEL,
            max_tokens={{ .MaxTokens }},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": req.message},
            ],
            stream=True,
        )
        for chunk in stream:
            delta = chunk.choices[0].delta
            if delta.content:
                yield f"data: {json.dumps({'text': delta.content})}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(generate(), media_type="text/event-stream")
{{ end }}

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
`

const fastapiRequirementsTmpl = `fastapi>=0.115.0
uvicorn[standard]>=0.30.0
{{ if eq .Provider "anthropic" }}anthropic>=0.40.0{{ else }}openai>=1.50.0{{ end }}
`

const fastapiReadmeTmpl = `# {{ .AgentName }} — API

Generated by [Trovery Forge](https://github.com/ceasarb/trovery-tools).

## Quick Start

` + "```" + `bash
pip install -r requirements.txt
uvicorn app:app --reload
` + "```" + `

## Endpoints

| Method | Path             | Description          |
|--------|------------------|----------------------|
| GET    | /health          | Health check         |
| POST   | /invoke          | Synchronous invoke   |
| POST   | /invoke/stream   | Streaming (SSE)      |

## Request

` + "```" + `json
{ "message": "Hello, agent!" }
` + "```" + `

## Configuration

Set your API key as an environment variable:

` + "```" + `bash
{{ if eq .Provider "anthropic" }}export ANTHROPIC_API_KEY=sk-...{{ else }}export OPENAI_API_KEY=sk-...{{ end }}
` + "```" + `
`

func (e *Exporter) exportFastAPI() (*ExportResult, error) {
	data, err := e.buildPythonData()
	if err != nil {
		return nil, fmt.Errorf("build fastapi data: %w", err)
	}

	app, err := renderTemplate("app.py", fastapiAppTmpl, data)
	if err != nil {
		return nil, fmt.Errorf("render app.py: %w", err)
	}

	reqs, err := renderTemplate("requirements.txt", fastapiRequirementsTmpl, data)
	if err != nil {
		return nil, fmt.Errorf("render requirements.txt: %w", err)
	}

	readme, err := renderTemplate("README.md", fastapiReadmeTmpl, data)
	if err != nil {
		return nil, fmt.Errorf("render README.md: %w", err)
	}

	if err := e.writeFile("app.py", app); err != nil {
		return nil, err
	}
	if err := e.writeFile("requirements.txt", reqs); err != nil {
		return nil, err
	}
	if err := e.writeFile("README.md", readme); err != nil {
		return nil, err
	}

	return &ExportResult{
		Format: FormatFastAPI,
		Files: []ExportedFile{
			{Path: "app.py", Description: "FastAPI application"},
			{Path: "requirements.txt", Description: "Python dependencies"},
			{Path: "README.md", Description: "Usage instructions"},
		},
	}, nil
}
