package export

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/ceasarb/trovery-tools/internal/forge/agent/config"
)

const pythonScriptTmpl = `#!/usr/bin/env python3
"""{{ .AgentName }} — Generated by Trovery Forge"""

import subprocess
import json
import sys
import os

# Provider: {{ .Provider }}
# Model: {{ .Model }}
{{ if eq .Provider "anthropic" }}
from anthropic import Anthropic

client = Anthropic()
MODEL = "{{ .Model }}"
{{ else }}
from openai import OpenAI

client = OpenAI()
MODEL = "{{ .Model }}"
{{ end }}

SYSTEM_PROMPT = """{{ .SystemPrompt }}"""

{{ if .HasBundledServers }}
# --- MCP Server Management ---

SERVER_COMMANDS = {
{{ range .BundledServers }}    "{{ .Name }}": "{{ .Command }}",
{{ end }}}

server_processes = {}


def start_servers():
    """Start all bundled MCP servers as subprocesses."""
    for name, cmd in SERVER_COMMANDS.items():
        parts = cmd.split()
        try:
            proc = subprocess.Popen(
                parts,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            server_processes[name] = proc
            print(f"  Started server: {name} (pid {proc.pid})")
        except Exception as e:
            print(f"  Failed to start {name}: {e}", file=sys.stderr)


def stop_servers():
    """Stop all running server subprocesses."""
    for name, proc in server_processes.items():
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
{{ end }}
{{ if .HasExternalServers }}
# External servers (connect via URL):
{{ range .ExternalServers }}# - {{ .Name }}: {{ .URL }}
{{ end }}{{ end }}

{{ if eq .Provider "anthropic" }}
def chat(user_message: str, messages: list) -> str:
    """Send a message and handle the tool-call loop."""
    messages.append({"role": "user", "content": user_message})

    while True:
        response = client.messages.create(
            model=MODEL,
            max_tokens={{ .MaxTokens }},
            system=SYSTEM_PROMPT,
            messages=messages,
        )

        # Collect assistant content
        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            # Extract final text
            for block in response.content:
                if hasattr(block, "text"):
                    return block.text
            return ""

        # Handle tool calls (placeholder — requires MCP client integration)
        tool_results = []
        for block in response.content:
            if block.type == "tool_use":
                print(f"  [tool] {block.name}({json.dumps(block.input)})")
                tool_results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps({"error": "Tool execution not wired in exported script"}),
                    }
                )

        messages.append({"role": "user", "content": tool_results})
{{ else }}
def chat(user_message: str, messages: list) -> str:
    """Send a message and handle the tool-call loop."""
    messages.append({"role": "user", "content": user_message})

    while True:
        response = client.chat.completions.create(
            model=MODEL,
            max_tokens={{ .MaxTokens }},
            messages=[{"role": "system", "content": SYSTEM_PROMPT}] + messages,
        )

        choice = response.choices[0]
        messages.append(choice.message)

        if choice.finish_reason != "tool_calls":
            return choice.message.content or ""

        # Handle tool calls (placeholder — requires MCP client integration)
        if choice.message.tool_calls:
            for tc in choice.message.tool_calls:
                print(f"  [tool] {tc.function.name}({tc.function.arguments})")
                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": tc.id,
                        "content": json.dumps({"error": "Tool execution not wired in exported script"}),
                    }
                )
{{ end }}

if __name__ == "__main__":
    print("{{ .AgentName }} (type 'quit' to exit)")
{{ if .HasBundledServers }}
    start_servers()
{{ end }}
    messages = []
    try:
        while True:
            try:
                user_input = input("You: ")
            except EOFError:
                break
            if user_input.strip().lower() in ("quit", "exit"):
                break
            response = chat(user_input, messages)
            print(f"Agent: {response}")
    except KeyboardInterrupt:
        pass
    finally:
{{ if .HasBundledServers }}        stop_servers()
{{ end }}        print("\nGoodbye.")
`

const requirementsTmpl = `{{ if eq .Provider "anthropic" }}anthropic>=0.40.0{{ else }}openai>=1.50.0{{ end }}
`

type pythonData struct {
	AgentName          string
	Provider           string
	Model              string
	SystemPrompt       string
	MaxTokens          int
	HasBundledServers  bool
	HasExternalServers bool
	BundledServers     []config.ServerRef
	ExternalServers    []config.ServerRef
	ToolsJSON          string
}

func (e *Exporter) buildPythonData() (*pythonData, error) {
	bundled, external := e.classifyServers()

	// Escape backticks and triple-quotes in the system prompt so it's safe inside """..."""
	safePrompt := strings.ReplaceAll(e.config.System, `"""`, `\"\"\"`)

	maxTokens := e.config.Model.MaxTokens
	if maxTokens == 0 {
		maxTokens = 4096
	}

	// Build a simple tools JSON (empty list — placeholder for MCP discovery)
	toolsJSON, _ := json.MarshalIndent([]any{}, "", "  ")

	return &pythonData{
		AgentName:          e.config.Name,
		Provider:           e.config.Model.Provider,
		Model:              e.config.Model.Model,
		SystemPrompt:       safePrompt,
		MaxTokens:          maxTokens,
		HasBundledServers:  len(bundled) > 0,
		HasExternalServers: len(external) > 0,
		BundledServers:     bundled,
		ExternalServers:    external,
		ToolsJSON:          string(toolsJSON),
	}, nil
}

func (e *Exporter) exportPython() (*ExportResult, error) {
	data, err := e.buildPythonData()
	if err != nil {
		return nil, fmt.Errorf("build python data: %w", err)
	}

	script, err := renderTemplate("agent.py", pythonScriptTmpl, data)
	if err != nil {
		return nil, fmt.Errorf("render agent.py: %w", err)
	}

	reqs, err := renderTemplate("requirements.txt", requirementsTmpl, data)
	if err != nil {
		return nil, fmt.Errorf("render requirements.txt: %w", err)
	}

	if err := e.writeFile("agent.py", script); err != nil {
		return nil, err
	}
	if err := e.writeFile("requirements.txt", reqs); err != nil {
		return nil, err
	}

	return &ExportResult{
		Format: FormatPython,
		Files: []ExportedFile{
			{Path: "agent.py", Description: "Standalone agent script"},
			{Path: "requirements.txt", Description: "Python dependencies"},
		},
	}, nil
}
