package deploy

import "fmt"

type cloudRunData struct {
	AgentName     string
	Provider      string
	APIKeyEnv     string
	Port          int
	Model         string
	MaxTokens     int
	BudgetMonthly float64
}

func (d *Deployer) buildCloudRunData() cloudRunData {
	return cloudRunData{
		AgentName:     d.config.Name,
		Provider:      d.config.Model.Provider,
		APIKeyEnv:     d.apiKeyEnv(),
		Port:          8080,
		Model:         d.config.Model.Model,
		MaxTokens:     d.config.Model.MaxTokens,
		BudgetMonthly: d.config.Settings.BudgetMonthly,
	}
}

const cloudRunMainTfTmpl = `# {{ .AgentName }} — Cloud Run deployment
# Generated by Trovery Forge
#
# Estimated cost: Cloud Run charges per request + CPU/memory time.
# Minimum instances = 0 means scale-to-zero (no idle cost).
# See: https://cloud.google.com/run/pricing

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# --- Secret Manager ---

resource "google_secret_manager_secret" "api_key" {
  secret_id = "{{ .AgentName }}-api-key"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "api_key" {
  secret      = google_secret_manager_secret.api_key.id
  secret_data = var.api_key
}

# --- Service Account ---

resource "google_service_account" "agent" {
  account_id   = "{{ .AgentName }}-sa"
  display_name = "{{ .AgentName }} Agent Service Account"
}

resource "google_secret_manager_secret_iam_member" "agent_access" {
  secret_id = google_secret_manager_secret.api_key.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.agent.email}"
}

# --- Cloud Run Service ---

resource "google_cloud_run_v2_service" "agent" {
  name     = var.service_name
  location = var.region

  template {
    service_account = google_service_account.agent.email

    scaling {
      min_instance_count = var.min_instances
      max_instance_count = var.max_instances
    }

    containers {
      image = var.image

      ports {
        container_port = {{ .Port }}
      }

      env {
        name = "{{ .APIKeyEnv }}"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.api_key.id
            version = "latest"
          }
        }
      }

      resources {
        limits = {
          cpu    = var.cpu
          memory = var.memory
        }
      }

      startup_probe {
        http_get {
          path = "/health"
          port = {{ .Port }}
        }
        initial_delay_seconds = 5
        period_seconds        = 5
      }

      liveness_probe {
        http_get {
          path = "/health"
          port = {{ .Port }}
        }
        period_seconds = 30
      }
    }
  }

  depends_on = [
    google_secret_manager_secret_version.api_key,
    google_secret_manager_secret_iam_member.agent_access,
  ]
}

# --- IAM: Allow unauthenticated invocation (toggle via variable) ---

resource "google_cloud_run_v2_service_iam_member" "invoker" {
  count    = var.allow_unauthenticated ? 1 : 0
  project  = var.project_id
  location = var.region
  name     = google_cloud_run_v2_service.agent.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}
`

const cloudRunVariablesTfTmpl = `# {{ .AgentName }} — Terraform variables

variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region for Cloud Run"
  type        = string
  default     = "us-central1"
}

variable "service_name" {
  description = "Cloud Run service name"
  type        = string
  default     = "{{ .AgentName }}"
}

variable "image" {
  description = "Container image (e.g., gcr.io/project/image:tag)"
  type        = string
}

variable "api_key" {
  description = "Provider API key (stored in Secret Manager)"
  type        = string
  sensitive   = true
}

variable "cpu" {
  description = "CPU limit"
  type        = string
  default     = "1"
}

variable "memory" {
  description = "Memory limit"
  type        = string
  default     = "512Mi"
}

variable "min_instances" {
  description = "Minimum instance count (0 = scale-to-zero)"
  type        = number
  default     = 0
}

variable "max_instances" {
  description = "Maximum instance count"
  type        = number
  default     = 5
}

variable "allow_unauthenticated" {
  description = "Allow unauthenticated invocations"
  type        = bool
  default     = false
}
`

const cloudRunOutputsTfTmpl = `# {{ .AgentName }} — Terraform outputs

output "service_url" {
  description = "Cloud Run service URL"
  value       = google_cloud_run_v2_service.agent.uri
}

output "service_account_email" {
  description = "Service account email"
  value       = google_service_account.agent.email
}
`

const cloudRunTfvarsTmpl = `# {{ .AgentName }} — Example terraform.tfvars
#
# Copy this to terraform.tfvars and fill in values.

project_id = "your-gcp-project"
region     = "us-central1"
image      = "gcr.io/your-project/{{ .AgentName }}:latest"
api_key    = "" # or use: TF_VAR_api_key env var

# min_instances = 0   # scale-to-zero (default)
# max_instances = 5
# allow_unauthenticated = false
`

func (d *Deployer) deployCloudRun() (*DeployResult, error) {
	data := d.buildCloudRunData()

	templates := []struct {
		path string
		tmpl string
		desc string
	}{
		{"cloud-run/main.tf", cloudRunMainTfTmpl, "Cloud Run service + Secret Manager + IAM"},
		{"cloud-run/variables.tf", cloudRunVariablesTfTmpl, "Input variables"},
		{"cloud-run/outputs.tf", cloudRunOutputsTfTmpl, "Output values (service URL)"},
		{"cloud-run/terraform.tfvars.example", cloudRunTfvarsTmpl, "Example variable values"},
	}

	var files []DeployedFile
	for _, t := range templates {
		content, err := renderTemplate(t.path, t.tmpl, data)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", t.path, err)
		}
		if err := d.writeFile(t.path, content); err != nil {
			return nil, err
		}
		files = append(files, DeployedFile{Path: t.path, Description: t.desc})
	}

	return &DeployResult{
		Target: TargetCloudRun,
		Files:  files,
		NextSteps: []string{
			"cd deploy/cloud-run",
			"cp terraform.tfvars.example terraform.tfvars  # fill in values",
			"terraform init",
			"terraform plan",
			"terraform apply",
		},
	}, nil
}
