package deploy

import "fmt"

type containerAppsData struct {
	AgentName string
	Provider  string
	APIKeyEnv string
	Port      int
	Model     string
}

func (d *Deployer) buildContainerAppsData() containerAppsData {
	return containerAppsData{
		AgentName: d.config.Name,
		Provider:  d.config.Model.Provider,
		APIKeyEnv: d.apiKeyEnv(),
		Port:      8080,
		Model:     d.config.Model.Model,
	}
}

const bicepMainTmpl = `// {{ .AgentName }} — Azure Container Apps deployment
// Generated by Demigo Forge
//
// Estimated cost: Container Apps charges per vCPU-second + memory-second.
// Min replicas = 0 means scale-to-zero (consumption plan).
// See: https://azure.microsoft.com/en-us/pricing/details/container-apps/

@description('Location for all resources')
param location string = resourceGroup().location

@description('Container Apps Environment name')
param environmentName string = '{{ .AgentName }}-env'

@description('Container App name')
param appName string = '{{ .AgentName }}'

@description('Container image')
param image string

@description('Key Vault name for secrets')
param keyVaultName string = '{{ .AgentName }}-kv'

@description('Provider API key')
@secure()
param apiKey string

@description('Minimum replicas (0 = scale-to-zero)')
param minReplicas int = 0

@description('Maximum replicas')
param maxReplicas int = 5

@description('CPU cores')
param cpu string = '0.5'

@description('Memory')
param memory string = '1Gi'

// --- Key Vault ---

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
  }
}

resource apiKeySecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'api-key'
  properties: {
    value: apiKey
  }
}

// --- Managed Identity ---

resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${appName}-identity'
  location: location
}

resource kvRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: keyVault
  name: guid(keyVault.id, managedIdentity.id, '4633458b-17de-408a-b874-0445c86b69e6')
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6') // Key Vault Secrets User
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// --- Container Apps Environment ---

resource environment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: environmentName
  location: location
  properties: {
    zoneRedundant: false
  }
}

// --- Container App ---

resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: appName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: environment.id
    configuration: {
      ingress: {
        external: true
        targetPort: {{ .Port }}
        transport: 'http'
      }
      secrets: [
        {
          name: 'api-key'
          keyVaultUrl: apiKeySecret.properties.secretUri
          identity: managedIdentity.id
        }
      ]
    }
    template: {
      containers: [
        {
          name: appName
          image: image
          resources: {
            cpu: json(cpu)
            memory: memory
          }
          env: [
            {
              name: '{{ .APIKeyEnv }}'
              secretRef: 'api-key'
            }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: {
                path: '/health'
                port: {{ .Port }}
              }
              periodSeconds: 30
            }
            {
              type: 'Readiness'
              httpGet: {
                path: '/ready'
                port: {{ .Port }}
              }
              periodSeconds: 10
            }
          ]
        }
      ]
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [
          {
            name: 'http-scaling'
            http: {
              metadata: {
                concurrentRequests: '10'
              }
            }
          }
        ]
      }
    }
  }
}

// --- Outputs ---

output fqdn string = containerApp.properties.configuration.ingress.fqdn
output appUrl string = 'https://${containerApp.properties.configuration.ingress.fqdn}'
`

const bicepParametersTmpl = `{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "image": {
      "value": "your-registry.azurecr.io/{{ .AgentName }}:latest"
    },
    "apiKey": {
      "value": ""
    },
    "location": {
      "value": "eastus"
    }
  }
}
`

func (d *Deployer) deployContainerApps() (*DeployResult, error) {
	data := d.buildContainerAppsData()

	templates := []struct {
		path string
		tmpl string
		desc string
	}{
		{"container-apps/main.bicep", bicepMainTmpl, "Container App + Key Vault + managed identity"},
		{"container-apps/parameters.json", bicepParametersTmpl, "Deployment parameters"},
	}

	var files []DeployedFile
	for _, t := range templates {
		content, err := renderTemplate(t.path, t.tmpl, data)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", t.path, err)
		}
		if err := d.writeFile(t.path, content); err != nil {
			return nil, err
		}
		files = append(files, DeployedFile{Path: t.path, Description: t.desc})
	}

	return &DeployResult{
		Target: TargetContainerApps,
		Files:  files,
		NextSteps: []string{
			"cd deploy/container-apps",
			"az group create --name rg-" + data.AgentName + " --location eastus",
			"az deployment group create --resource-group rg-" + data.AgentName + " --template-file main.bicep --parameters @parameters.json",
		},
	}, nil
}
