package deploy

import "fmt"

type actionsData struct {
	AgentName string
	Provider  string
	APIKeyEnv string
	HasEval   bool
}

func (d *Deployer) buildActionsData() actionsData {
	return actionsData{
		AgentName: d.config.Name,
		Provider:  d.config.Model.Provider,
		APIKeyEnv: d.apiKeyEnv(),
		HasEval:   true,
	}
}

const validateWorkflowTmpl = `# {{ .AgentName }} — Validate on PR
# Generated by Demigo Forge
name: Validate

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Demigo Forge
        run: |
          curl -sSL https://github.com/ceasarb/demigo-tools/releases/latest/download/demigo-forge_linux_amd64.tar.gz | tar xz
          sudo mv demi-forge /usr/local/bin/

      - name: Validate servers
        run: |
          for dir in servers/*/; do
            if [ -f "$dir/demi.toml" ]; then
              echo "Validating $dir"
              demi forge server validate --path "$dir"
            fi
          done

      - name: Test servers
        run: |
          for dir in servers/*/; do
            if [ -f "$dir/demi.toml" ]; then
              echo "Testing $dir"
              demi forge server test --path "$dir"
            fi
          done

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: "1"
`

const evalWorkflowTmpl = `# {{ .AgentName }} — Eval on merge
# Generated by Demigo Forge
name: Eval

on:
  push:
    branches: [main]

jobs:
  eval:
    runs-on: ubuntu-latest
    env:
      {{ .APIKeyEnv }}: ${{ "{{" }} secrets.{{ .APIKeyEnv }} {{ "}}" }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Demigo Forge
        run: |
          curl -sSL https://github.com/ceasarb/demigo-tools/releases/latest/download/demigo-forge_linux_amd64.tar.gz | tar xz
          sudo mv demi-forge /usr/local/bin/

      - name: Run agent eval
        run: demi forge agent eval {{ .AgentName }} --format json

      - name: Upload eval results
        uses: actions/upload-artifact@v4
        with:
          name: eval-results
          path: .demi/forge/eval_results.db
`

const deployWorkflowTmpl = `# {{ .AgentName }} — Deploy on tag
# Generated by Demigo Forge
name: Deploy

on:
  push:
    tags: ["v*"]

env:
  IMAGE_NAME: {{ .AgentName }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ "{{" }} github.actor {{ "}}" }}
          password: ${{ "{{" }} secrets.GITHUB_TOKEN {{ "}}" }}

      - name: Extract tag
        id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ "{{" }} github.repository {{ "}}" }}/${{ "{{" }} env.IMAGE_NAME {{ "}}" }}:${{ "{{" }} steps.tag.outputs.version {{ "}}" }}
            ghcr.io/${{ "{{" }} github.repository {{ "}}" }}/${{ "{{" }} env.IMAGE_NAME {{ "}}" }}:latest
`

func (d *Deployer) deployGitHubActions() (*DeployResult, error) {
	data := d.buildActionsData()

	templates := []struct {
		path string
		tmpl string
		desc string
	}{
		{".github/workflows/validate.yml", validateWorkflowTmpl, "Validate + test servers on PR"},
		{".github/workflows/eval.yml", evalWorkflowTmpl, "Run agent eval on merge to main"},
		{".github/workflows/deploy.yml", deployWorkflowTmpl, "Build, push, and deploy on tag"},
		{".github/workflows/benchmark.yml", benchmarkWorkflowTmpl, "Performance benchmarks on release"},
	}

	var files []DeployedFile
	for _, t := range templates {
		content, err := renderTemplate(t.path, t.tmpl, data)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", t.path, err)
		}
		if err := d.writeFile(t.path, content); err != nil {
			return nil, err
		}
		files = append(files, DeployedFile{Path: t.path, Description: t.desc})
	}

	return &DeployResult{
		Target: TargetGitHubActions,
		Files:  files,
		NextSteps: []string{
			fmt.Sprintf("Add %s to repository secrets", data.APIKeyEnv),
			"Push to trigger validate workflow on PR",
			"Tag a release to trigger deploy workflow: git tag v0.1.0 && git push --tags",
		},
	}, nil
}
